### ISSUE TITLE
Message: invalid element state

### ISSUE THREAD

**Issue by sixiaojie** [975278060/selenuim_comment#1]
拉下代码，安装依赖后，执行一直错误。错误如下： 
Traceback (most recent call last):
  File "/Users/sijie/PycharmProjects/pythonProject2/main.py", line 172, in <module>
    denglu(s1, s2)
  File "/Users/sijie/PycharmProjects/pythonProject2/main.py", line 65, in denglu
    huadong()
  File "/Users/sijie/PycharmProjects/pythonProject2/main.py", line 127, in huadong
    pinglun(i,driver)
  File "/Users/sijie/PycharmProjects/pythonProject2/main.py", line 137, in pinglun
    driver.find_element_by_name("rv_comment").clear()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 93, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state

**Comment by sixiaojie** [comment]
调试发现了 ，登陆时候被拦截了 ，说网络环境异常，感觉调试多了
